name: Master branch updater.

on: workflow_dispatch
# don't need that
#on:
#  release:
#    types: released

jobs:
  User-agent:
    runs-on: ubuntu-slim
    steps:
      - uses: desktop-app/action_code_updater@master
        with:
          type: "dev-to-master"
