name: User-agent updater.

on:
  repository_dispatch:
    types: ["Restart user_agent_updater workflow."]
# all these updates made in upstream
#  schedule:
#    # At 00:00 on day-of-month 1.
#    - cron: "0 0 1 * *"

jobs:
  User-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: desktop-app/action_code_updater@master
        with:
          type: "user-agent"
